# Generated by Django 5.2.6 on 2026-08-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('REQUESTER', 'Requester'), ('TECHNICIAN', 'Technician'), ('MANAGER', 'Manager'), ('ADMIN', 'Administrator')], default='REQUESTER', max_length=20),
        ),
    ]
