FROM python:3.13-slim

WORKDIR /app

COPY requirements/base.txt ./requirements/base.txt
COPY requirements/ci.txt ./requirements/ci.txt

RUN pip install --no-cache-dir -r requirements/ci.txt

COPY . .
