# Generated by Django 5.2.6 on 2026-08-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name of the category.', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the category.')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name of the priority.', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the priority.')),
                ('level', models.PositiveSmallIntegerField(help_text='Numeric level used to sort priorities.', unique=True)),
            ],
            options={
                'verbose_name': 'Priority',
                'verbose_name_plural': 'Priorities',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name of the ticket status.', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the ticket status.')),
                ('is_final', models.BooleanField(default=False, help_text='Whether this status represents the end of a ticket lifecycle.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this status can be used for new tickets.')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statuses',
                'ordering': ['name'],
            },
        ),
    ]
