# Generated by Django 5.2.6 on 2026-08-14 20:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0004_assignment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="assignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("ticket",),
                name="unique_primary_assignment_per_ticket",
            ),
        ),
    ]
